### ISSUE TITLE
Support rustls when native-tls is not available

### ISSUE THREAD

**Issue by Chronophylos** [robotty/twitch-irc-rs#106]

**Comment by RAnders00** [comment]
Can you elaborate a bit on this, are there platforms that native-tls does not support?

**Comment by Chronophylos** [comment]
I'd like to choose between native-tls and rustls with a cargo feature.

When I try to compile my program with [cross](https://github.com/rust-embedded/cross) it fails to compile because openssl is not available.

I am usually using rustls instead of native-tls and it would be nice to depend only on one of them.

**Comment by ilyazzz** [comment]
> I'd like to choose between native-tls and rustls with a cargo feature.
> 
> When I try to compile my program with [cross](https://github.com/rust-embedded/cross) it fails to compile because openssl is not available.
> 
> I am usually using rustls instead of native-tls and it would be nice to depend only on one of them.

You can specify
`native-tls = { version = "", features = ["vendored"] }`
In your cargo.toml so that cross will compile openssl for the target platform itself.

**Comment by RAnders00** [comment]
Still, that is a fair use case. I'll look into finally adding rustls support to this crate.

**Comment by RAnders00** [comment]
Will be implemented by #113

**Comment by RAnders00** [comment]
Sorry for taking so long, but you might be pleased to hear v3.0.0 has been released just now, which includes the new feature.

**Comment by Chronophylos** [comment]
Pag
