### ISSUE TITLE
`TokenStorage` trait signature doesn't allow for UAT initialisation

### ISSUE THREAD

**Issue by teotwaki** [robotty/twitch-irc-rs#155]
Hi,

The current version of `TokenStorage` has the following signature for `load_token`:

```rust
async fn load_token(&mut self) -> Result<UserAccessToken, Self::LoadError>;
```

I expected that upon failure (e.g.: `FileNotFound`), `RefreshingLoginCredentials` would fetch credentials from twitch and then attempt to store them in the `TokenStorage`. However, this appears to [not be the case](https://github.com/robotty/twitch-irc-rs/blob/601e0d262bd34c831a4f0003283a7db3dcced2fe/src/login.rs#L234):

```rust
        let mut current_token = token_storage
            .load_token()
            .await
            .map_err(RefreshingLoginError::LoadError)?;
```

I see three options:

- Upon initialisation of my `TokenStorage`, initialise a fake `UserAccessToken` with an intentionally expired date. This seems quite hackish.
- Modify `RefreshingLoginCredentials<S>::get_credentials()` to first try to update the credentials prior to bailing out after receiving a `LoadError`. This seems suboptimal.
- Modify the `TokenStorage` trait to return `Result<Option<UserAccessToken>, Self::LoadError>` to indicate to `RefreshingLoginCredentials<S>::get_credentials()` that the credential has never been initialised. `get_credentials` would simply try to `update_token` prior to bailing out.

Again, I'm happy to make the necessary code changes and provide a PR for this.

There is, obviously, the ever glaring option that I'm an idiot who misunderstood the API. In that case, please feel free to admonish me and correct the error of my ways.

**Comment by teotwaki** [comment]
I clearly expected Twitch auth to be much more logical than it actually is. I think I need to go back to the drawing board on this one.

**Comment by RAnders00** [comment]
> I expected that […] `RefreshingLoginCredentials` would fetch credentials from twitch

I assume you found out about that yourself now given your comment - indeed you have to get the first authorization for your bot manually using your web browser, and with that initial token you can then "seed" the mechanism in this library which is responsible for refreshing it as needed.
