### ISSUE TITLE
Can I have an event if user clam reward using channel points?

### ISSUE THREAD

**Issue by SirMishaa** [robotty/twitch-irc-rs#159]
Hello ! 

I'd like to have an event when user claim reward with his channel points. Does the library support it? 

https://help.twitch.tv/s/article/channel-points-guide?language=en_US

Regards

**Comment by Nerixyz** [comment]
You can't get the full reward and redemption through IRC, but you can get its reward-id through the `custom-reward-id` tag: [`privmsg.source`](https://docs.rs/twitch-irc/latest/twitch_irc/message/struct.PrivmsgMessage.html#structfield.source)[`.tags`](https://docs.rs/twitch-irc/latest/twitch_irc/message/struct.PrivmsgMessage.html#structfield.source)[`.0`](https://docs.rs/twitch-irc/latest/twitch_irc/message/struct.IRCTags.html#structfield.0)`.get("custom-reward-id")`

If you want to get the full reward and redemption, you need to use [PubSub](https://dev.twitch.tv/docs/pubsub) or [EventSub](https://dev.twitch.tv/docs/eventsub).

**Comment by SirMishaa** [comment]
Okay, thank you very much for the explanation!
