### ISSUE TITLE
Add support for reply-parent tags

### ISSUE THREAD

**Issue by Retoon** [robotty/twitch-irc-rs#187]
I noticed there wasn't support for reply-parent tags, these tags contain information about a message a user is replying to in chat, the tags are optional and not present when the message is not in reply to another message.
see: https://dev.twitch.tv/docs/irc/tags/#twitch-irc-tags

I suggest something like a `ReplyParent` struct type that contains the five reply-parent related tags, `msg-id`, `user-login`, `user-login`, `display-name`, `msg-body`

if i have time i'll try to fork and implement it but i'm not terribly familiar with developing crates or libraries, but will give it a shot.

**Comment by Retoon** [comment]
I opened a pull request ( #189 ). This is my first time doing a (proper) pull request so there's a good chance i missed something that i needed to do.

**Comment by DanielHe4rt** [comment]
The project still being maintained?

**Comment by Retoon** [comment]
> The project still being maintained?

I don't know why you're asking in this issue specifically, but i'm sure @RAnders00 is just busy.

**Comment by RAnders00** [comment]
Added via #189
