### ISSUE TITLE
Can't join channels anymore

### ISSUE THREAD

**Issue by Thomas485** [robotty/twitch-irc-rs#191]
I can't join channels anymore.

I tried the example from the readme, but it doesn't work either.

`client.join` is returning `Ok(())`, but `client.get_channel_status` returns `(true, false)` and the `incoming_messages.recv().await` is blocking indefinitely. (`try_recv` returns `Ok(Empty)` )

**Comment by Thomas485** [comment]
I figured it out, I forgot about my new firewall that blocked irc…

Sorry for the ticket.

**Comment by RAnders00** [comment]
A tip for the future - this crate emits debug and error messages via `tracing` :) It‘s quite easy to have them displayed in your application:

https://github.com/robotty/twitch-irc-rs/blob/2e3e36b646630a0e6059896d7fece413180fb253/examples/simple_listener.rs#L7

Then set the `RUST_LOG` environment variable to `twitch_irc=debug`
