### ISSUE TITLE
[RUSTSEC-2023-0052] webpki: CPU denial of service in certificate path building

### ISSUE THREAD

**Issue by ZoeS17** [robotty/twitch-irc-rs#192]
It appears this applies likely because of `webpki-roots = { version = "0.22", optional = true }` at [L#48](https://github.com/robotty/twitch-irc-rs/blob/2e3e36b646630a0e6059896d7fece413180fb253/Cargo.toml#L48C1-L48C53) in Cargo.toml

----
**Crate**:     webpki
**Version**:   0.22.0
**Title**:     webpki: CPU denial of service in certificate path building
**Date**:      2023-08-22
**ID**:        RUSTSEC-2023-0052
**URL**:       https://rustsec.org/advisories/RUSTSEC-2023-0052
**Severity**:  7.5 (high)
**Solution**:  No fixed upgrade is available!

----
<details>
<summary>Output of `cargo audit` after a standard `cargo build`:</summary>

```bash
webpki 0.22.0
├── webpki-roots 0.22.6
│   ├── twitch-irc 5.0.0
│   ├── reqwest 0.11.14
│   │   └── twitch-irc 5.0.0
│   └── async-tungstenite 0.17.2
│       └── twitch-irc 5.0.0
├── tungstenite 0.17.3
│   └── async-tungstenite 0.17.2
├── tokio-rustls 0.23.4
│   ├── twitch-irc 5.0.0
│   ├── reqwest 0.11.14
│   ├── hyper-rustls 0.23.2
│   │   └── reqwest 0.11.14
│   └── async-tungstenite 0.17.2
└── rustls 0.20.8
    ├── tungstenite 0.17.3
    ├── tokio-rustls 0.23.4
    ├── reqwest 0.11.14
    └── hyper-rustls 0.23.2
```
</details>

This was fixed in denoland/deno#20285 by updating to name `webpki-roots` to `0.25.2` which removes the inherit dependency on `webpki`. They also had to bump their `reqwest` version to `0.11.20`(which would likely get picked up with a simple `cargo update`)

It looks like an update would fix things. I don't know if that should/can get caught up in #189 or if that should land separately.

**Comment by ZoeS17** [comment]
Addendum: it appears that `async-tungstenite = { version = "0.17", features = ["tokio-runtime"], optional = true }` [#L30](https://github.com/robotty/twitch-irc-rs/blob/2e3e36b646630a0e6059896d7fece413180fb253/Cargo.toml#L30C1-L30C88) in `cargo.toml` pins a version that can also be updated to `0.22` or `0.23` both of which fix their underlying pin of `webpki-roots` to a version that alleviates this issue as well.

**Comment by RAnders00** [comment]
Fix released to crates.io as version 5.0.1

**Comment by ZoeS17** [comment]
Thank you for such a prompt response. I hope this wasn't to out of protocol. I hope your day/night goes well too.
