### ISSUE TITLE
Set wanted channels command bug 

### ISSUE THREAD

**Issue by AbstractiveNord** [robotty/twitch-irc-rs#204]
If you pass enough big hashset to set wanted channels method, only part of targeted channels will be connected, monitored via Prometheus metrics.

**Comment by RAnders00** [comment]
1. Can you make a minimal example to replicate this?
2. Are you using anonymous connections, or are you logging in?

**Comment by AbstractiveNord** [comment]
> 1. Can you make a minimal example to replicate this?
> 
>     2. Are you using anonymous connections, or are you logging in?
> 
>     3. Do all the channels you are trying to connect actually exist on Twitch?

I've tried metrics example with join to about 2000 channels, and problem was displayed as constant difference between wanted and server channels metrics. That's not related to rate-limits, but some connections was failed, that's also displayed via other metrics. Looks like set wanted channels doesn't care about failed connections.

**Comment by RAnders00** [comment]
Could you run the example with the environment variable `RUST_LOG=twitch_irc=debug`?

How big is this difference?

Joining a lot of channels this way is supported and works for me, I actually use less conservative settings for the rate limits in production. Running 161000 channels at the moment, with almost all of them also confirmed by the server:
![IMG_0477](https://github.com/robotty/twitch-irc-rs/assets/1629196/8ac6c66c-c75f-4576-897b-8f51407ea76a)

Also note that joining a lot of channels takes a considerable amount of time. The default limit is 90 every 2 seconds.

>  Looks like set wanted channels doesn't care about failed connections.

This is incorrect, failed connections cause a retry.

If you don‘t mind, please share your code.

**Comment by RAnders00** [comment]
> Can you say, what will happen if random channel will be banned by Twitch?

Check the documentation above for a reference, but what happens is:
- If the streamer is banned after you join their channel, nothing bad will happen. You stay connected to their chat. If you stay connected for the entire duration of the ban (so, say, the full week or whatever), you will, without needing to do anything, receive messages from that channel again after the unban. [`get_channel_status()`](https://docs.rs/twitch-irc/latest/twitch_irc/client/struct.TwitchIRCClient.html#method.get_channel_status) will be `(true, true)` before, during the ban, and after.
- If the streamer is banned before you try and join the channel, [`get_channel_status()`](https://docs.rs/twitch-irc/latest/twitch_irc/client/struct.TwitchIRCClient.html#method.get_channel_status) for that channel will be `(true, false)` to indicate that the channel could not be joined. You can retry to join by periodically calling `join()` again.

> Also, if streamer start raid, how it may affect these metrics?

Nothing. It does not affect anything. You will receive an incoming message from Twitch announcing the raid, if that is what you mean. But the client will not switch over to the channel that is raided.

**Comment by AbstractiveNord** [comment]
Found problem on my side, closing issue, thanks for help.

**Comment by RAnders00** [comment]
If you don't mind, I'm curious as to what the issue was? Maybe I can improve the documentation or the examples?

**Comment by AbstractiveNord** [comment]
> If you don't mind, I'm curious as to what the issue was? Maybe I can improve the documentation or the examples?

I've got a problem with my code wrapper on top of your awesome crate. Probably it's good idea to have a internal queue for detailed information about connections, their current states, and changes. I am building dynamic controller software on top of your crate, and whole issue is my fault.

**Comment by RAnders00** [comment]
Feel free to make a feature request for anything you feel like could be added. I'm always open to adding support for use-cases I've not thought of or have not had.

**Comment by AbstractiveNord** [comment]
How you configure client config for 162K channels?

**Comment by AbstractiveNord** [comment]
Sometime code says
```
ERROR client_loop: twitch_irc::client::event_loop: Pool connection 68 has failed due to error (removing it): Did not receive a PONG back after sending PING
```
Can I get that event in code? How it should be treat?

**Comment by RAnders00** [comment]
Please make a separate feature request for that!
