### ISSUE TITLE
Underlying transport failed to connect.

### ISSUE THREAD

**Issue by AbstractiveNord** [robotty/twitch-irc-rs#209]
```
ERROR client_loop: twitch_irc::client::event_loop: Pool connection 2103 has failed due to error (removing it): Underlying transport failed to connect: error:10080002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:300:, error:05880002:x509 certificate routines:X509_load_cert_file_ex:system lib:../crypto/x509/by_file.c:100:, error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file, error:80000018:system library:file_open_dir:reason(2):../providers/implementations/storemgmt/file_store.c:183:Calling OPENSSL_DIR_read("/usr/lib/ssl/certs"), error:80000018:system library:file_ctrl:reason(2):../crypto/bio/bss_file.c:297:calling fopen(/usr/lib/ssl/certs/f387163d.0, r), error:10080002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:300:, error:05880002:x509 certificate routines:X509_load_cert_file_ex:system lib:../crypto/x509/by_file.c:100:, error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file, error:80000018:system library:file_open_dir:reason(2):../providers/implementations/storemgmt/file_store.c:183:Calling OPENSSL_DIR_read("/usr/lib/ssl/certs"), error:80000018:system library:file_ctrl:reason(2):../crypto/bio/bss_file.c:297:calling fopen(/usr/lib/ssl/certs/f387163d.0, r), error:10080002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:300:, error:05880002:x509 certificate routines:X509_load_cert_file_ex:system lib:../crypto/x509/by_file.c:100:, error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file, error:80000018:system library:file_open_dir:reason(2):../providers/implementations/storemgmt/file_store.c:183:Calling OPENSSL_DIR_read("/usr/lib/ssl/certs"), error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (unable to get local issuer certificate)
```
After that error reconnections goes cycle, with same result.

**Comment by RAnders00** [comment]
This error seems to come from OpenSSL not being able to open certificate files/directories, either something with `/usr/lib/ssl/certs` or `/usr/lib/ssl/certs/f387163d.0`, reason seems to be "No such file or directory" (errno 2). Either way, this is not an error that can stem from this library, seems to be an issue somewhere in your system, possibly a broken symlink or similar. Basically anything using the `native-tls` crate should fail to work on your system- If you can't get it worked out, try using something like `reqwest` to make an HTTPS connection.

**Comment by AbstractiveNord** [comment]
> This error seems to come from OpenSSL not being able to open certificate files/directories, either something with `/usr/lib/ssl/certs` or `/usr/lib/ssl/certs/f387163d.0`, reason seems to be "No such file or directory" (errno 2). Either way, this is not an error that can stem from this library, seems to be an issue somewhere in your system, possibly a broken symlink or similar. Basically anything using the `native-tls` crate should fail to work on your system- If you can't get it worked out, try using something like `reqwest` to make an HTTPS connection.

It's kinda weird because it happens if `twitch-irc-rs` unit create over a thousand and a little connections. Before that limit, everything's fine.
