### ISSUE TITLE
Reduce heap usage and allocations

### ISSUE THREAD

**Issue by AbstractiveNord** [robotty/twitch-irc-rs#210]
Let's use more smart string types, such as FastStr provided via [fast_str crate](https://crates.io/crates/fast-str).

**Comment by Nerixyz** [comment]
Seems like a duplicate of #178. As for the type, I think in many cases a `&str` pointing into the raw message can be fine as long as there aren't any escape characters.

**Comment by RAnders00** [comment]
Thanks @Nerixyz, I had felt like there was a ticket for that before but must have overlooked it.
