### ISSUE TITLE
Update docs to use tokio's recv instead of next

### ISSUE THREAD

**Issue by Segfavlt** [robotty/twitch-irc-rs#27]
Update the docs tokio's recv() instead of next(). https://tokio-rs.github.io/tokio/doc/tokio/sync/mpsc/struct.UnboundedReceiver.html

**Comment by RAnders00** [comment]
Unless I'm missing something, `next()` is the same as `recv()`, except that for `next()` you have to have `StreamExt` in scope, correct?

In that case, I agree, the documentation will be updated to use recv.

**Comment by Segfavlt** [comment]
I believe that is correct yes. I found when following the examples to the letter, with tokio v 0.2.22 due to other dependencies in my project it refused to compile. switching to `recv()` was the simplest fix in my case.
