### ISSUE TITLE
whispers

### ISSUE THREAD

**Issue by daxara** [robotty/twitch-irc-rs#55]
I'm building a little bot and i want it also to respond to whispers.
i cant seem to find a function to call for sending whispers.
am i missing something?

**Comment by RAnders00** [comment]
There's no built-in method yet. You can use `client.privmsg("bot_name".to_owned(), format!("/w {} {}", recipient_name, message))` meanwhile.

**Comment by RAnders00** [comment]
Has been consolidated into #85

**Comment by RAnders00** [comment]
A native method to send whispers will be included in the next `twitch_irc` release. See also #164
